Repository knative-extensions/net-http01, pull requests merged in 2020-08, with the labels that each got.

#54 Pin some knative.dev deps to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#55 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#56 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#57 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L
