Repository knative-extensions/net-http01, pull requests merged in 2020-06, with the labels that each got.

#30 Bump module to go1.14 & use vendored certificate conformance tests
  go.mod
  go.sum
  test/conformance/certificate_test.go
  test/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/serving/test/conformance/certificate/http01/run.go
  vendor/knative.dev/serving/test/conformance/certificate/utils.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#33 Some minor clean up post-refactoring.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/controller.go
  pkg/reconciler/certificate/resources/secret.go
Labels: approved, cla: yes, lgtm, size/S

#23 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#38 Rename the http01 controller to avoid collisions
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS
