Repository knative-extensions/net-http01, pull requests merged in 2020-09, with the labels that each got.

#60 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#61 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#62 Add linting config and fix issues.
  .golangci.yaml
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/resources/secret_test.go
Labels: approved, cla: yes, lgtm, size/S

#63 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#65 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#66 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#67 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#69 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#70 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#71 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#72 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#73 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#75 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#76 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#77 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#78 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#79 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#80 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#81 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
