Repository knative-extensions/net-http01, pull requests merged in 2021-05, with the labels that each got.

#207 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#209 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#210 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#211 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#212 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#214 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#215 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
