Repository knative-extensions/net-http01, pull requests merged in 2021-01, with the labels that each got.

#169 Pass the appropriate options to the update path as well.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
Labels: approved, cla: yes, lgtm, size/XS

#170 Allow Certificate names that aren't DNS-1035 labels.
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/resources/service.go
  pkg/reconciler/certificate/resources/service_test.go
Labels: approved, cla: yes, kind/bug, lgtm, ok-to-test, size/L

#171 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#172 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#173 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#174 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#175 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#176 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#177 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#179 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
