Repository knative-extensions/net-http01, pull requests merged in 2022-12, with the labels that each got.

#436 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#440 [release-1.7] pull in cert conformance fixes
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#441 [release-1.6] pull in cert conformance fixes
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#443 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#444 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
