Repository knative-extensions/net-http01, pull requests merged in 2022-05, with the labels that each got.

#374 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#375 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#376 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#377 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#378 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#379 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#382 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#383 Add secret label for filtering informers
  pkg/reconciler/certificate/resources/secret.go
  pkg/reconciler/certificate/resources/secret_test.go
Labels: approved, lgtm, size/XS

#385 [main] Format markdown
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/XS

#381 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/timeout/timeout.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
