Repository knative-extensions/net-http01, pull requests merged in 2022-10, with the labels that each got.

#421 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#422 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#423 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#426 [release-1.8] Skip HTTP01 conformance test in 1.8 release
  test/conformance/certificate_test.go
Labels: approved, size/XS

#428 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
