Repository knative-extensions/net-http01, pull requests merged in 2023-02, with the labels that each got.

#453 Use serving-writers and reviewers teams
  OWNERS
Labels: approved, lgtm, size/XS

#454 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#455 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#457 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#459 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#458 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#460 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#462 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#469 [release-1.8] trigger to build release with go1.19.6
  go.mod
Labels: approved, lgtm, size/XS
