Repository knative-extensions/net-http01, pull requests merged in 2023-12, with the labels that each got.

#572 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#573 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#576 [release-1.11] Bump to fix serving/#14732
  go.mod
Labels: approved, lgtm, size/XS

#575 [release-1.12] Bump to fix serving/#14732
  go.mod
Labels: approved, lgtm, size/XS

#574 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/SECURITY.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version6.go
  vendor/github.com/google/uuid/version7.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/event/keys/util.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
