Repository knative-extensions/net-http01, pull requests merged in 2023-10, with the labels that each got.

#549 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#550 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#551 [release-1.10] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: approved, lgtm, size/XS

#555 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#557 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#558 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#559 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#560 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#561 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
