Repository knative-extensions/net-http01, pull requests merged in 2023-09, with the labels that each got.

#528 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#529 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#530 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#531 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#532 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#534 Fix securityContext settings - allows running the controller in a restricted
  config/controller.yaml
Labels: approved, lgtm, size/XS

#536 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#537 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/M

#538 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#539 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#540 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#544 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#542 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#545 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#546 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/M
